### ISSUE TITLE
Agent should export node ips in pod status 

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/agent#223] opened 2021-07-16 10:21 UTC
In order for service discovery based on pods to work for collecting metrics via Prometheus or Victoriametrics our pods need to publish ip addresses in the status field.

This excerpt shows what a kubernetes pod sets, a first trial with both hostIP and podIP was successful.

```yaml
apiVersion: v1
kind: Pod
metadata:
...
spec:
...
status:
 ...
  hostIP: 10.10.92.14
  podIP: 10.42.0.6
  podIPs:
  - ip: 10.42.0.6
```

We should further investigate, what field Prometheus actually uses and if there are reasons to set both.

**Comment by maltesander** [comment] 2021-07-16 12:41
The podIP is the one Prometheus requires. For us podIP = hostIP, so i dont see a problem with setting both?

**Comment by siegfriedweber** [comment] 2021-07-16 17:54
Duplicate of #222

**Closed** 2021-07-19 08:01 UTC
