### ISSUE TITLE
Investigate pod deletion happening before processes are stopped

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/agent#38] opened 2021-01-20 09:32 UTC
@maltesander has noticed that his spark processes when he restarts them quite often need to find a new port because the old process is still up and running.
We need to look at adding finalizers to pods and maybe have a "shutting down" state that allows to wait for the process to stop.

**Comment by lfrancke** [comment] 2021-05-12 09:29
duplicate of #136

**Closed by lfrancke** 2021-05-12 09:29 UTC
Labels: priority/high, status/duplicate, type/bug
